---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: _data/translations.yml
  label: "\U0001F1E9\U0001F1EA\U0001F1EC\U0001F1E7"
- type: document
  path: _data/founders.yml
  label: Stifter
- type: document
  path: _data/current.yml
  label: Teasers
- type: document
  path: _data/transactions.yml
  label: Transaktionen
upload_dir: assets/img/uploads
public_path: "/assets/img/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:-:year::month::day:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
